import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1713499000000 implements MigrationInterface {
    name = 'InitialSchema1713499000000'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('SUPER_ADMIN', 'COMPANY_SUPER_ADMIN', 'COMPANY_STAFF', 'CUSTOMER')`);
        await queryRunner.query(`CREATE TYPE "public"."users_preferredcurrency_enum" AS ENUM('NGN', 'USD')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "firstName" character varying(100) NOT NULL, "lastName" character varying(100) NOT NULL, "email" character varying(255) NOT NULL, "passwordHash" character varying(255) NOT NULL, "phone" character varying(20), "role" "public"."users_role_enum" NOT NULL DEFAULT 'CUSTOMER', "countryCode" character varying(3) NOT NULL DEFAULT 'NG', "preferredCurrency" "public"."users_preferredcurrency_enum" NOT NULL DEFAULT 'NGN', "emailVerified" boolean NOT NULL DEFAULT false, "totpSecret" character varying(255), "twoFactorEnabled" boolean NOT NULL DEFAULT false, "backupCodes" character varying array, "failedLoginAttempts" integer NOT NULL DEFAULT '0', "lockedUntil" TIMESTAMP WITH TIME ZONE, "lastLoginAt" TIMESTAMP WITH TIME ZONE, "avatarUrl" character varying(512), "permissions" text, CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "categories" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "name" character varying(200) NOT NULL, "slug" character varying(250) NOT NULL, "description" text, "alias" character varying(200), "imageUrl" character varying(512), "sortOrder" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "metaTitle" character varying(200), "metaDescription" character varying(500), "mpath" character varying DEFAULT '', "parentId" character varying(26), CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_420d9f679d41281f282f5bc7d0" ON "categories" ("slug") `);
        await queryRunner.query(`CREATE TABLE "products" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "name" character varying(300) NOT NULL, "slug" character varying(350) NOT NULL, "description" text, "shortDescription" text, "isActive" boolean NOT NULL DEFAULT true, "isFeatured" boolean NOT NULL DEFAULT false, "categoryId" character varying(26), "attributes" jsonb, "metaTitle" character varying(200), "metaDescription" character varying(500), "tags" text, CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_464f927ae360106b783ed0b410" ON "products" ("slug") `);
        await queryRunner.query(`CREATE TABLE "product_variants" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "productId" character varying(26) NOT NULL, "sku" character varying(100) NOT NULL, "name" character varying(200), "retailPriceNgn" bigint NOT NULL, "retailPriceUsd" bigint NOT NULL, "wholesalePriceNgn" bigint NOT NULL, "wholesalePriceUsd" bigint NOT NULL, "compareAtPriceNgn" bigint, "compareAtPriceUsd" bigint, "costPriceNgn" bigint, "weightKg" numeric(10,3), "isActive" boolean NOT NULL DEFAULT true, "trackInventory" boolean NOT NULL DEFAULT true, "options" jsonb, "barcode" character varying(100), "sortOrder" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_281e3f2c55652d6a22c0aa59fd7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_46f236f21640f9da218a063a86" ON "product_variants" ("sku") `);
        await queryRunner.query(`CREATE TYPE "public"."product_media_mediatype_enum" AS ENUM('IMAGE', 'VIDEO')`);
        await queryRunner.query(`CREATE TABLE "product_media" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "productId" character varying(26) NOT NULL, "url" character varying(1024) NOT NULL, "altText" character varying(300), "mediaType" "public"."product_media_mediatype_enum" NOT NULL DEFAULT 'IMAGE', "sortOrder" integer NOT NULL DEFAULT '0', "sizes" jsonb, CONSTRAINT "PK_09d4639de8082a32aa27f3ac9a6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "wishlist_items" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "userId" character varying(26) NOT NULL, "productId" character varying(26) NOT NULL, "variantId" character varying(26), "note" character varying(500), CONSTRAINT "UQ_wishlist_user_product" UNIQUE ("userId", "productId"), CONSTRAINT "PK_0bd52924a97cda208ed2a07bd69" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3167e7490f12ed329a36703d98" ON "wishlist_items" ("userId") `);
        await queryRunner.query(`CREATE TABLE "roles" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "name" character varying(100) NOT NULL, "description" character varying(500), "permissions" jsonb NOT NULL DEFAULT '[]', "isSystem" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_648e3f5447f725579d7d4ffdfb" ON "roles" ("name") `);
        await queryRunner.query(`CREATE TABLE "terminals" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "code" character varying(50) NOT NULL, "name" character varying(200) NOT NULL, "branchId" character varying(26) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_cd9f1bbe36836bffd5217d3fe60" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_terminals_code" ON "terminals" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_terminals_branchId" ON "terminals" ("branchId") `);
        await queryRunner.query(`CREATE TABLE "user_branches" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "userId" character varying(26) NOT NULL, "branchId" character varying(26) NOT NULL, CONSTRAINT "PK_45063e37edfcad5acaa0158c53a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_user_branches_userId" ON "user_branches" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_user_branches_branchId" ON "user_branches" ("branchId") `);
        await queryRunner.query(`CREATE TABLE "branches" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "code" character varying(50) NOT NULL, "name" character varying(200) NOT NULL, "warehouseCode" character varying(100) NOT NULL, "address" jsonb, "phone" character varying(30), "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_7f37d3b42defea97f1df0d19535" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_branches_code" ON "branches" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_branches_warehouseCode" ON "branches" ("warehouseCode") `);
        await queryRunner.query(`CREATE TYPE "public"."pos_sessions_status_enum" AS ENUM('ACTIVE', 'AWAITING_PAYMENT', 'COMPLETED', 'VOIDED')`);
        await queryRunner.query(`CREATE TABLE "pos_sessions" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "terminalId" character varying(26) NOT NULL, "branchId" character varying(26) NOT NULL, "openedByStaffId" character varying(26) NOT NULL, "status" "public"."pos_sessions_status_enum" NOT NULL DEFAULT 'ACTIVE', "cart" jsonb NOT NULL, "version" integer NOT NULL DEFAULT '0', "openedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "closedAt" TIMESTAMP WITH TIME ZONE, "resultOrderNumber" character varying(20), "resultOrderId" character varying(26), CONSTRAINT "PK_ea6a8d8a95103f03518a0f72c45" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_pos_sessions_terminalId" ON "pos_sessions" ("terminalId") `);
        await queryRunner.query(`CREATE INDEX "IDX_pos_sessions_branchId" ON "pos_sessions" ("branchId") `);
        await queryRunner.query(`CREATE TYPE "public"."pos_sync_jobs_status_enum" AS ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'DEAD_LETTER')`);
        await queryRunner.query(`CREATE TABLE "pos_sync_jobs" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "transactionId" character varying(64) NOT NULL, "terminalId" character varying(100) NOT NULL, "transactionPayload" jsonb NOT NULL, "status" "public"."pos_sync_jobs_status_enum" NOT NULL DEFAULT 'PENDING', "retryCount" integer NOT NULL DEFAULT '0', "errorMessage" text, "orderId" character varying(26), CONSTRAINT "PK_81900f0f3a1eef199db911f01fd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_519de9232ba4af3f1184ba1e1c" ON "pos_sync_jobs" ("transactionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_80452945b58501838e49c7873a" ON "pos_sync_jobs" ("status") `);
        await queryRunner.query(`CREATE TYPE "public"."orders_status_enum" AS ENUM('DRAFT', 'PENDING_PAYMENT', 'PAID', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'RETURN_REQUESTED', 'RETURN_APPROVED', 'RETURNED', 'REFUNDED')`);
        await queryRunner.query(`CREATE TYPE "public"."orders_channel_enum" AS ENUM('STOREFRONT', 'ADMIN', 'POS')`);
        await queryRunner.query(`CREATE TYPE "public"."orders_paymentmethod_enum" AS ENUM('MONIEPOINT', 'PAYSTACK', 'STRIPE', 'CASH', 'BANK_TRANSFER', 'POS_TERMINAL')`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "orderNumber" character varying(20) NOT NULL, "userId" character varying(26), "guestEmail" character varying(255), "status" "public"."orders_status_enum" NOT NULL DEFAULT 'DRAFT', "channel" "public"."orders_channel_enum" NOT NULL DEFAULT 'STOREFRONT', "branchId" character varying(26), "currency" character varying(3) NOT NULL DEFAULT 'NGN', "subtotal" bigint NOT NULL DEFAULT '0', "discountTotal" bigint NOT NULL DEFAULT '0', "shippingTotal" bigint NOT NULL DEFAULT '0', "taxTotal" bigint NOT NULL DEFAULT '0', "grandTotal" bigint NOT NULL DEFAULT '0', "paymentMethod" "public"."orders_paymentmethod_enum", "paymentReference" character varying(255), "paidAt" TIMESTAMP WITH TIME ZONE, "shippingAddress" jsonb, "couponCode" character varying(50), "discountType" character varying(20), "discountAppliedBy" character varying(26), "discountAppliedByName" character varying(100), "discountAppliedAt" TIMESTAMP WITH TIME ZONE, "idempotencyKey" character varying(64), "trackingNumber" character varying(100), "carrier" character varying(100), "shippedAt" TIMESTAMP WITH TIME ZONE, "deliveredAt" TIMESTAMP WITH TIME ZONE, "customerNote" text, "staffNote" text, CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_59b0c3b34ea0fa5562342f2414" ON "orders" ("orderNumber") `);
        await queryRunner.query(`CREATE INDEX "IDX_151b79a83ba240b0cb31b2302d" ON "orders" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_873d9661d948ee484150cf4c73" ON "orders" ("branchId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1881ab845832ad82c4e45f5fe3" ON "orders" ("idempotencyKey") `);
        await queryRunner.query(`CREATE TABLE "order_items" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "orderId" character varying(26) NOT NULL, "variantId" character varying(26) NOT NULL, "productName" character varying(300) NOT NULL, "variantName" character varying(200), "sku" character varying(100) NOT NULL, "quantity" integer NOT NULL, "unitPrice" bigint NOT NULL, "lineTotal" bigint NOT NULL, "discountAmount" bigint NOT NULL DEFAULT '0', "imageUrl" character varying(512), "options" jsonb, CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."order_status_history_fromstatus_enum" AS ENUM('DRAFT', 'PENDING_PAYMENT', 'PAID', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'RETURN_REQUESTED', 'RETURN_APPROVED', 'RETURNED', 'REFUNDED')`);
        await queryRunner.query(`CREATE TYPE "public"."order_status_history_tostatus_enum" AS ENUM('DRAFT', 'PENDING_PAYMENT', 'PAID', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'RETURN_REQUESTED', 'RETURN_APPROVED', 'RETURNED', 'REFUNDED')`);
        await queryRunner.query(`CREATE TABLE "order_status_history" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "orderId" character varying(26) NOT NULL, "fromStatus" "public"."order_status_history_fromstatus_enum" NOT NULL, "toStatus" "public"."order_status_history_tostatus_enum" NOT NULL, "changedBy" character varying(26), "reason" text, CONSTRAINT "PK_e6c66d853f155531985fc4f6ec8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."push_tokens_platform_enum" AS ENUM('ios', 'android')`);
        await queryRunner.query(`CREATE TABLE "push_tokens" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "userId" character varying(26) NOT NULL, "expoPushToken" character varying(200) NOT NULL, "platform" "public"."push_tokens_platform_enum", "deviceLabel" character varying(200), "isActive" boolean NOT NULL DEFAULT true, "lastUsedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_32734e87f299c29ca3878861f4f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_push_tokens_userId" ON "push_tokens" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_push_tokens_expoPushToken" ON "push_tokens" ("expoPushToken") `);
        await queryRunner.query(`CREATE TYPE "public"."stock_movements_kind_enum" AS ENUM('RECEIPT', 'SALE', 'RESERVATION', 'RELEASE', 'RETURN', 'ADJUSTMENT', 'TRANSFER_OUT', 'TRANSFER_IN')`);
        await queryRunner.query(`CREATE TABLE "stock_movements" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "variantId" character varying(26) NOT NULL, "kind" "public"."stock_movements_kind_enum" NOT NULL, "quantity" integer NOT NULL, "warehouseCode" character varying(100) NOT NULL DEFAULT 'DEFAULT', "referenceId" character varying(100), "referenceType" character varying(50), "reason" text, "createdBy" character varying(26), "clientLineId" character varying(36), CONSTRAINT "PK_57a26b190618550d8e65fb860e7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b1e10f38c51868fba8bac1e12c" ON "stock_movements" ("variantId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e572a492b1723d71b00ec47e91" ON "stock_movements" ("referenceId", "referenceType", "variantId", "kind") WHERE "referenceId" IS NOT NULL`);
        await queryRunner.query(`CREATE TABLE "stock_levels" ("variantId" character varying(26) NOT NULL, "warehouseCode" character varying(100) NOT NULL DEFAULT 'DEFAULT', "onHand" integer NOT NULL DEFAULT '0', "reserved" integer NOT NULL DEFAULT '0', "lastMovementAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), CONSTRAINT "PK_d5ada753ccdb64f64e28f2b5d6c" PRIMARY KEY ("variantId", "warehouseCode"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d5ada753ccdb64f64e28f2b5d6" ON "stock_levels" ("variantId", "warehouseCode") `);
        await queryRunner.query(`CREATE TABLE "customers" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "userId" character varying(26) NOT NULL, "totalOrders" integer NOT NULL DEFAULT '0', "totalSpentNgn" bigint NOT NULL DEFAULT '0', "totalSpentUsd" bigint NOT NULL DEFAULT '0', "lastOrderAt" TIMESTAMP WITH TIME ZONE, "avgOrderValueNgn" bigint NOT NULL DEFAULT '0', "tags" jsonb NOT NULL DEFAULT '[]', "notes" text, "marketingOptIn" boolean NOT NULL DEFAULT false, "marketingOptInAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b8512aa9cef03d90ed5744c94d" ON "customers" ("userId") `);
        await queryRunner.query(`CREATE TABLE "customer_addresses" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "customerId" character varying(26) NOT NULL, "label" character varying(50) NOT NULL DEFAULT 'Home', "firstName" character varying(100) NOT NULL, "lastName" character varying(100) NOT NULL, "line1" character varying(500) NOT NULL, "line2" character varying(500), "city" character varying(100) NOT NULL, "state" character varying(100) NOT NULL, "postalCode" character varying(20), "country" character varying(3) NOT NULL DEFAULT 'NG', "phone" character varying(20), "isDefault" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_336bda7b0a0cd04241f719fc834" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."coupons_discounttype_enum" AS ENUM('PERCENTAGE', 'FIXED_AMOUNT', 'FREE_SHIPPING')`);
        await queryRunner.query(`CREATE TYPE "public"."coupons_status_enum" AS ENUM('ACTIVE', 'EXPIRED', 'DISABLED')`);
        await queryRunner.query(`CREATE TABLE "coupons" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "code" character varying(50) NOT NULL, "description" character varying(200), "discountType" "public"."coupons_discounttype_enum" NOT NULL, "discountValue" bigint NOT NULL, "currency" character varying(3), "minimumOrderAmount" bigint NOT NULL DEFAULT '0', "maximumDiscount" bigint NOT NULL DEFAULT '0', "usageLimit" integer NOT NULL DEFAULT '0', "usageLimitPerCustomer" integer NOT NULL DEFAULT '1', "timesUsed" integer NOT NULL DEFAULT '0', "status" "public"."coupons_status_enum" NOT NULL DEFAULT 'ACTIVE', "startsAt" TIMESTAMP WITH TIME ZONE, "expiresAt" TIMESTAMP WITH TIME ZONE, "applicableProductIds" jsonb NOT NULL DEFAULT '[]', "applicableCategoryIds" jsonb NOT NULL DEFAULT '[]', "createdBy" character varying(26), CONSTRAINT "PK_d7ea8864a0150183770f3e9a8cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e025109230e82925843f2a14c4" ON "coupons" ("code") `);
        await queryRunner.query(`CREATE TABLE "cart_items" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "userId" character varying(26) NOT NULL, "variantId" character varying(26), "productId" character varying(26), "quantity" integer NOT NULL, "productName" character varying(200) NOT NULL, "productSlug" character varying(200) NOT NULL, "variantName" character varying(200), "sku" character varying(100) NOT NULL, "priceNgn" bigint NOT NULL, "priceUsd" bigint NOT NULL, "options" jsonb, "imageUrl" character varying(500), CONSTRAINT "UQ_cart_user_variant" UNIQUE ("userId", "variantId"), CONSTRAINT "PK_6fccf5ec03c172d27a28a82928b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_84e765378a5f03ad9900df3a9b" ON "cart_items" ("userId") `);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "userId" character varying(26) NOT NULL, "tokenHash" character varying(64) NOT NULL, "family" character varying(26) NOT NULL, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "revoked" boolean NOT NULL DEFAULT false, "ipAddress" character varying(45), "userAgent" character varying(512), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_610102b60fea1455310ccd299d" ON "refresh_tokens" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c25bc63d248ca90e8dcc1d92d0" ON "refresh_tokens" ("tokenHash") `);
        await queryRunner.query(`CREATE INDEX "IDX_968936751ab847471635be8dc0" ON "refresh_tokens" ("family") `);
        await queryRunner.query(`CREATE TABLE "password_reset_tokens" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "userId" character varying(26) NOT NULL, "tokenHash" character varying(64) NOT NULL, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "used" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_d16bebd73e844c48bca50ff8d3d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d6a19d4b4f6c62dcd29daa497e" ON "password_reset_tokens" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1143abb8c3fad8b06dd857a8c9" ON "password_reset_tokens" ("tokenHash") `);
        await queryRunner.query(`CREATE TABLE "email_verification_tokens" ("id" character varying(26) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "userId" character varying(26) NOT NULL, "tokenHash" character varying(64) NOT NULL, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "used" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_417a095bbed21c2369a6a01ab9a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_10f285d038feb767bf7c2da14b" ON "email_verification_tokens" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_90489f8f3368c45f461e90efbe" ON "email_verification_tokens" ("tokenHash") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" character varying(26) NOT NULL, "actorId" character varying(26) NOT NULL, "actorEmail" character varying(255) NOT NULL, "actorRole" character varying(50) NOT NULL, "action" character varying(100) NOT NULL, "resourceType" character varying(50) NOT NULL, "resourceId" character varying(26) NOT NULL, "description" text, "previousState" jsonb, "newState" jsonb, "changes" jsonb, "ipAddress" character varying(45), "userAgent" character varying(512), "channel" character varying(20) NOT NULL DEFAULT 'admin', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2dc33f7f3c22e2e7badafca1d1" ON "audit_logs" ("actorId") `);
        await queryRunner.query(`CREATE INDEX "IDX_cee5459245f652b75eb2759b4c" ON "audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_fb731b6c9ec3271068b48a0786" ON "audit_logs" ("resourceType") `);
        await queryRunner.query(`CREATE INDEX "IDX_b41c13e0a4212c95088d102981" ON "audit_logs" ("resourceId") `);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_9a6f051e66982b5f0318981bcaa" FOREIGN KEY ("parentId") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_ff56834e735fa78a15d0cf21926" FOREIGN KEY ("categoryId") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD CONSTRAINT "FK_f515690c571a03400a9876600b5" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_media" ADD CONSTRAINT "FK_50e3945c6150d80b69b5f18515a" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wishlist_items" ADD CONSTRAINT "FK_3167e7490f12ed329a36703d980" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wishlist_items" ADD CONSTRAINT "FK_485ece8ab9b569d1c560144aa25" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wishlist_items" ADD CONSTRAINT "FK_60d00c5eb5d7373097aa5e1668b" FOREIGN KEY ("variantId") REFERENCES "product_variants"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "terminals" ADD CONSTRAINT "FK_1678490768bc6fd67654b1e3596" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_branches" ADD CONSTRAINT "FK_730d741ac106176848e5b3c96cd" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_branches" ADD CONSTRAINT "FK_d4bfb1375daa4e5e17f3def2403" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pos_sessions" ADD CONSTRAINT "FK_3380f23548dd79ab54a9b6dce79" FOREIGN KEY ("terminalId") REFERENCES "terminals"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pos_sessions" ADD CONSTRAINT "FK_97d2a3299d21f93cf6b70b17db8" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pos_sessions" ADD CONSTRAINT "FK_c8357db79e6d5365c28b3e54fac" FOREIGN KEY ("openedByStaffId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_151b79a83ba240b0cb31b2302d1" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_status_history" ADD CONSTRAINT "FK_689db3835e5550e68d26ca32676" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "push_tokens" ADD CONSTRAINT "FK_95b226ff93ba9b9edfd06136be0" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "FK_b1e10f38c51868fba8bac1e12c9" FOREIGN KEY ("variantId") REFERENCES "product_variants"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_levels" ADD CONSTRAINT "FK_382b617b6109816b300db459bc8" FOREIGN KEY ("variantId") REFERENCES "product_variants"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "FK_b8512aa9cef03d90ed5744c94d7" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_addresses" ADD CONSTRAINT "FK_7bd088b1c8d3506953240ebf030" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "FK_84e765378a5f03ad9900df3a9ba" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "FK_5a27845bc2d79be6f1fa3d2c036" FOREIGN KEY ("variantId") REFERENCES "product_variants"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "FK_72679d98b31c737937b8932ebe6" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_610102b60fea1455310ccd299de" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" ADD CONSTRAINT "FK_d6a19d4b4f6c62dcd29daa497e2" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_verification_tokens" ADD CONSTRAINT "FK_10f285d038feb767bf7c2da14b3" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "email_verification_tokens" DROP CONSTRAINT "FK_10f285d038feb767bf7c2da14b3"`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" DROP CONSTRAINT "FK_d6a19d4b4f6c62dcd29daa497e2"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_610102b60fea1455310ccd299de"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "FK_72679d98b31c737937b8932ebe6"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "FK_5a27845bc2d79be6f1fa3d2c036"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "FK_84e765378a5f03ad9900df3a9ba"`);
        await queryRunner.query(`ALTER TABLE "customer_addresses" DROP CONSTRAINT "FK_7bd088b1c8d3506953240ebf030"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "FK_b8512aa9cef03d90ed5744c94d7"`);
        await queryRunner.query(`ALTER TABLE "stock_levels" DROP CONSTRAINT "FK_382b617b6109816b300db459bc8"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "FK_b1e10f38c51868fba8bac1e12c9"`);
        await queryRunner.query(`ALTER TABLE "push_tokens" DROP CONSTRAINT "FK_95b226ff93ba9b9edfd06136be0"`);
        await queryRunner.query(`ALTER TABLE "order_status_history" DROP CONSTRAINT "FK_689db3835e5550e68d26ca32676"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_151b79a83ba240b0cb31b2302d1"`);
        await queryRunner.query(`ALTER TABLE "pos_sessions" DROP CONSTRAINT "FK_c8357db79e6d5365c28b3e54fac"`);
        await queryRunner.query(`ALTER TABLE "pos_sessions" DROP CONSTRAINT "FK_97d2a3299d21f93cf6b70b17db8"`);
        await queryRunner.query(`ALTER TABLE "pos_sessions" DROP CONSTRAINT "FK_3380f23548dd79ab54a9b6dce79"`);
        await queryRunner.query(`ALTER TABLE "user_branches" DROP CONSTRAINT "FK_d4bfb1375daa4e5e17f3def2403"`);
        await queryRunner.query(`ALTER TABLE "user_branches" DROP CONSTRAINT "FK_730d741ac106176848e5b3c96cd"`);
        await queryRunner.query(`ALTER TABLE "terminals" DROP CONSTRAINT "FK_1678490768bc6fd67654b1e3596"`);
        await queryRunner.query(`ALTER TABLE "wishlist_items" DROP CONSTRAINT "FK_60d00c5eb5d7373097aa5e1668b"`);
        await queryRunner.query(`ALTER TABLE "wishlist_items" DROP CONSTRAINT "FK_485ece8ab9b569d1c560144aa25"`);
        await queryRunner.query(`ALTER TABLE "wishlist_items" DROP CONSTRAINT "FK_3167e7490f12ed329a36703d980"`);
        await queryRunner.query(`ALTER TABLE "product_media" DROP CONSTRAINT "FK_50e3945c6150d80b69b5f18515a"`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP CONSTRAINT "FK_f515690c571a03400a9876600b5"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_ff56834e735fa78a15d0cf21926"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_9a6f051e66982b5f0318981bcaa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b41c13e0a4212c95088d102981"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fb731b6c9ec3271068b48a0786"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cee5459245f652b75eb2759b4c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2dc33f7f3c22e2e7badafca1d1"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_90489f8f3368c45f461e90efbe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_10f285d038feb767bf7c2da14b"`);
        await queryRunner.query(`DROP TABLE "email_verification_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1143abb8c3fad8b06dd857a8c9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d6a19d4b4f6c62dcd29daa497e"`);
        await queryRunner.query(`DROP TABLE "password_reset_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_968936751ab847471635be8dc0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c25bc63d248ca90e8dcc1d92d0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_610102b60fea1455310ccd299d"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_84e765378a5f03ad9900df3a9b"`);
        await queryRunner.query(`DROP TABLE "cart_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e025109230e82925843f2a14c4"`);
        await queryRunner.query(`DROP TABLE "coupons"`);
        await queryRunner.query(`DROP TYPE "public"."coupons_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."coupons_discounttype_enum"`);
        await queryRunner.query(`DROP TABLE "customer_addresses"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b8512aa9cef03d90ed5744c94d"`);
        await queryRunner.query(`DROP TABLE "customers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d5ada753ccdb64f64e28f2b5d6"`);
        await queryRunner.query(`DROP TABLE "stock_levels"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e572a492b1723d71b00ec47e91"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b1e10f38c51868fba8bac1e12c"`);
        await queryRunner.query(`DROP TABLE "stock_movements"`);
        await queryRunner.query(`DROP TYPE "public"."stock_movements_kind_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_push_tokens_expoPushToken"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_push_tokens_userId"`);
        await queryRunner.query(`DROP TABLE "push_tokens"`);
        await queryRunner.query(`DROP TYPE "public"."push_tokens_platform_enum"`);
        await queryRunner.query(`DROP TABLE "order_status_history"`);
        await queryRunner.query(`DROP TYPE "public"."order_status_history_tostatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."order_status_history_fromstatus_enum"`);
        await queryRunner.query(`DROP TABLE "order_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1881ab845832ad82c4e45f5fe3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_873d9661d948ee484150cf4c73"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_151b79a83ba240b0cb31b2302d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_59b0c3b34ea0fa5562342f2414"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TYPE "public"."orders_paymentmethod_enum"`);
        await queryRunner.query(`DROP TYPE "public"."orders_channel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."orders_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_80452945b58501838e49c7873a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_519de9232ba4af3f1184ba1e1c"`);
        await queryRunner.query(`DROP TABLE "pos_sync_jobs"`);
        await queryRunner.query(`DROP TYPE "public"."pos_sync_jobs_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_pos_sessions_branchId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_pos_sessions_terminalId"`);
        await queryRunner.query(`DROP TABLE "pos_sessions"`);
        await queryRunner.query(`DROP TYPE "public"."pos_sessions_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_branches_warehouseCode"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_branches_code"`);
        await queryRunner.query(`DROP TABLE "branches"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_branches_branchId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_branches_userId"`);
        await queryRunner.query(`DROP TABLE "user_branches"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_terminals_branchId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_terminals_code"`);
        await queryRunner.query(`DROP TABLE "terminals"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_648e3f5447f725579d7d4ffdfb"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3167e7490f12ed329a36703d98"`);
        await queryRunner.query(`DROP TABLE "wishlist_items"`);
        await queryRunner.query(`DROP TABLE "product_media"`);
        await queryRunner.query(`DROP TYPE "public"."product_media_mediatype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_46f236f21640f9da218a063a86"`);
        await queryRunner.query(`DROP TABLE "product_variants"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_464f927ae360106b783ed0b410"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_420d9f679d41281f282f5bc7d0"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_preferredcurrency_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
    }

}
